language: scala
scala:
- 2.11.12
- 2.12.8
- 2.13.0
sudo: false
jdk:
- oraclejdk8
- oraclejdk9
- openjdk10
node_js:
- 8
before_script:
  - curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -x
script:
- sbt ++$TRAVIS_SCALA_VERSION boopickleJVM/test boopickleJS/test boopickleNative/test shapelessJVM/test shapelessJS/test shapelessNative/test
# Tricks to avoid unnecessary cache updates, from
# http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
